### ISSUE TITLE
装了这个插件但没有装paddleocr会出现的bug

### ISSUE THREAD

**Issue by niucattle** [hsyhhssyy/amiyabot-arknights-hsyhhssyy-enhanced#1]
![2 52S~IH 8NAQDLQ2G~M`VT](https://user-images.githubusercontent.com/118875129/213916534-cab357bf-35dd-40d0-816f-c5b59bd5df33.png)
这是装了paddleocr之前的情况，装了之后就消失了
我让其他出现这种情况的人直接把插件删除，也都恢复正常了
![7`HSKTTX@P}W2R8X545 K2P](https://user-images.githubusercontent.com/118875129/213916649-ce8194fa-f001-46d9-8dca-65ca3f6254ee.png)
这是后台的报错
![8bc26ccb52a02546c407f89d2708d549](https://user-images.githubusercontent.com/118875129/213916724-9983a62e-63ee-4594-a51b-c79650df9a73.png)

**Comment by niucattle** [comment]
如果不安装paddleocr 先发兔兔公招再发图片会提示图片识别错误
我安装了paddleocr后这种情况消失了
别人卸载了这个插件后这种情况也消失了

**Comment by niucattle** [comment]
但是直接发图片的话 是正常的（虽然兔兔有概率没识别到）

**Comment by hsyhhssyy** [comment]
可能是一个潜在的冲突导致的，我检查一下，多谢

**Comment by hsyhhssyy** [comment]
我仔细看了一下，我怀疑其实没有报错，是获取微博那个插件报错了，正好赶上了你这个消息。
获取微博那个插件，本来就经常会报错，因为微博会封扫他网站的ip一段时间。

而且，我尝试了几个猜测，都没有复现，不确定是什么情况导致的，

我只能说，实在不行，没有安装paddle ocr就别安装这个插件了，毕竟除去paddle ocr，另一个关卡掉率那个功能也不是特别有用。
或者你有其他能够提供的信息也好，比如更完整的报错信息，或者能100%复现问题的操作步骤。

**Comment by niucattle** [comment]
报错确实没有
复现简单 只要安装兔兔原版的公招插件和增强查询的插件就行
我刚新开了个号实验了一下
只安装了兔兔互动 兔兔公招 和增强查询
不安装paddleocr
先发兔兔公招再发图片会失败
后台就提示 短路后的公招查询1

**Comment by niucattle** [comment]
![JPG ~48D557%YM RPRDV@OK](https://user-images.githubusercontent.com/118875129/215542245-83609961-0142-4677-912b-96712d36de05.png)

**Comment by niucattle** [comment]
![image](https://user-images.githubusercontent.com/118875129/215542335-2ee87518-5ef8-411d-a28e-21532e55d36a.png)

**Comment by niucattle** [comment]
![image](https://user-images.githubusercontent.com/118875129/215542490-e6a47d59-42e5-4b15-b376-6d8eba8dff24.png)

**Comment by niucattle** [comment]
在安装之前是正常使用的

**Comment by hsyhhssyy** [comment]
"短路后的公招查询1"不是一个错误，他只是一个没删干净的提示信息。
至于图片识别失败，是因为你装了这个插件又没装paddle ocr，就识别失败了....

目前的插件Api暂时没能力做到检查到你没装paddle ocr就把控制权交还给原生插件。如果是用百度云的用户，可能就只能不装这个插件了。

后续我考虑把这两个功能分开成两个插件好了，这样用百度云的还能利用上掉率查询。

**Comment by niucattle** [comment]
是这样的，不过我们这些使用者看到那么多插件肯定是能装上多少是多少（bushi 
然后在啥都不知道的情况下 出现这种问题 也不会明白到底是哪出错了
我的流程就是 认为百度ocr 的api填错了，然后检查一遍发现没错
然后去问官方频道，那的人也认为是api填错了，
又去问万能的群友 他们告诉我他们的机器人也这样 可能这功能就这样
后来我仔细看了看插件发现这个问题，我就把paddleocr装上了，然后没问题了
然后就有了接下来的提的issue
如果可以的话，建议在插件那提一下这个问题

**Comment by hsyhhssyy** [comment]
我提议嘴吧，虽然有没有人看两说。
