### ISSUE TITLE
使用地图查询功能时报错

### ISSUE THREAD

**Issue by ykinsoul** [hsyhhssyy/amiyabot-arknights-hsyhhssyy-enhanced#3]
兔兔版本6.0.14
使用Mirai框架
增强查询插件已更新至v1.3
未安装paddleocr
公招可正常使用，查询地图功能会报错
![)`G8}}2WMD G$DFMN{MQETI](https://user-images.githubusercontent.com/71212242/222061505-db50c029-c23e-4924-bf21-b7d78601ec6e.png)
似乎和 <a href="https://github.com/hsyhhssyy/amiyabot-arknights-hsyhhssyy-enhanced/issues/2">issue#2</a> 中的报错是同一原因
![0559b040ccde23920764d6f563a7481d_216753390-cf741e94-89a4-47bc-a176-59b4a9effbbf](https://user-images.githubusercontent.com/71212242/222061910-51dfa9e1-5a50-4cd0-ada9-9a1c1666c315.png)

**Comment by hsyhhssyy** [comment]
我更新了一个1.5新版，你试一下好了没有

**Comment by ykinsoul** [comment]
更新后可以用了，感谢！
